# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x03mcp\"1\n\x0fGetToolsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\"D\n\x04Tool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11parameters_schema\x18\x03 \x01(\t\"N\n\x10GetToolsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x05tools\x18\x02 \x03(\x0b\x32\t.mcp.Tool\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"P\n\x12\x45xecuteToolRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\ttool_name\x18\x02 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x03 \x01(\t\"E\n\x13\x45xecuteToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\x8f\x01\n\nMCPService\x12?\n\x10GetRelevantTools\x12\x14.mcp.GetToolsRequest\x1a\x15.mcp.GetToolsResponse\x12@\n\x0b\x45xecuteTool\x12\x17.mcp.ExecuteToolRequest\x1a\x18.mcp.ExecuteToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTOOLSREQUEST']._serialized_start=18
  _globals['_GETTOOLSREQUEST']._serialized_end=67
  _globals['_TOOL']._serialized_start=69
  _globals['_TOOL']._serialized_end=137
  _globals['_GETTOOLSRESPONSE']._serialized_start=139
  _globals['_GETTOOLSRESPONSE']._serialized_end=217
  _globals['_EXECUTETOOLREQUEST']._serialized_start=219
  _globals['_EXECUTETOOLREQUEST']._serialized_end=299
  _globals['_EXECUTETOOLRESPONSE']._serialized_start=301
  _globals['_EXECUTETOOLRESPONSE']._serialized_end=370
  _globals['_MCPSERVICE']._serialized_start=373
  _globals['_MCPSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
